name: Skyworks Project
favicon: null
layout_spectrum: 1
typography_spectrum: 0.4769
title: Skyworks Project
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#132028'
    - '#919ca6'
    - '#1e3858'
    - '#f2f2f2'
    - '#4f5e72'
  brandStrength: 0.9375
  lightness: 0.8125
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
